### ISSUE TITLE
Governance testing: forum

### ISSUE THREAD

**Issue by apetrovskiy** [neonlabsorg/neon-e2e#62]

**Comment by gigimon** [comment]
Our forum was tested in https://forum.neon-labs.org/ for basic functionality:
1. User auth workflow (registration, verify email, login, logout). We don't have captcha but other example sites (forums.solana.com doesn't has captcha too)
2. Basic forum functionality (create post, create comment, delete post)
3. Basic admin functionality (login, delete post, user management)
